### ISSUE TITLE
Add imagery

### ISSUE THREAD

**Issue by zeke800** [sgcderek/sgcderek.github.io#1]
I actually received some off axis HRPT also :)

Can you please add it to your page?

https://zeke800.github.io/SAT/meteor_m2.html

**Comment by zeke800** [comment]
bump

**Comment by sgcderek** [comment]
I can embed your images in jpeg form and credit just like I did it with the one from hmdsamarasekara if that's ok with you

**Comment by zeke800** [comment]
Thank you very much for replying!! Frankly, I would really love that. However, if possible, most of the images are noisy, so could you please select (in your opinion) the best ones please?

Thank you so much!

**Comment by sgcderek** [comment]
Added two samples with a link to the original article
